//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpBilling.EntityFr
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISData
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public string Consignment_No { get; set; }
        public string Booking_Station { get; set; }
        public string Sender_Name { get; set; }
        public string Delivery_Destination { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public string Receiver_Name { get; set; }
        public string Invoice_No { get; set; }
        public Nullable<double> Cargo_Value { get; set; }
        public string Mode { get; set; }
        public Nullable<int> Box_No { get; set; }
        public Nullable<double> C_Weight_KG { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Risk_Surcharge_Percentage { get; set; }
        public Nullable<double> Risk_FOV_Amount_A { get; set; }
        public Nullable<double> Fright_Amount_B { get; set; }
        public Nullable<double> Pickup_Charges_C { get; set; }
        public Nullable<double> A_B_C_Total_D { get; set; }
        public Nullable<double> Fuel_Surcharge_Percentage_E { get; set; }
        public Nullable<double> Sub_Total_D_E { get; set; }
        public string To_Pay { get; set; }
        public Nullable<double> GST_Total { get; set; }
        public Nullable<System.DateTime> EDD_Date { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> Days { get; set; }
        public string Remark { get; set; }
        public string Delay_Reason { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
    }
}
